# theme: jekyll-theme-minimal
title: "Kyaw May Pyone Shinn"
description: "Data Analyst . Business Intelligence and Analyst"
baseurl: "" # keep empty for user.github.io repo; else "/repo-name"
url: "https://Kyaw-May-Pyone-Shinn.github.io"
source: .
