title: "Kyaw May Pyone Shinn"
description: "Data Analyst | Business Analyst | Business Intelligence Portfolio"
baseurl: ""
url: "https://kyaw-may-pyone-shinn.github.io"

markdown: kramdown

plugins:
  - jekyll-seo-tag
